---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: budget
spec:
  encryptedData:
    postgres-password: AgAYbbAYgQYQ8erlrJuTbrIxgS+s61UZL9yjCnCOcq+B9wmh3tjyzrYs/ZuV4C9yJevcytdkw0LHG5e0255SgCZvNWUb/oWp3AKhsDn++ZroeNARIKobAPsaj92Vmw6v9w9IjmDRRZ59kDm362qOPTFhDBnA35GLRdhaHZTUWIn45AjjOKG4nistpsMIP4+h14RyKOs7ng7UkslWBT6sFs4pB99rS/AiQ7UImCxyPtUzN8wNhe13UzNMdU+BdJHugTCG8w2ey4RgKlNbe/le0pQDk33i65h3iclPBDV/Smjscp+vSEuIW+KqmFUXMFidkuR7CPwsXUooN+xHYieokMFjhnKz7H7A9guor1xKAWrBRBqoUQ+QTzXvf0xSc0UDCyk31/NiC+QPBQmTl6LCn/4HC7OcsqqSIZHzSN+gjCs4uXow0lDHrUVsMFBx7S/wgoYSO/24MdRp5D3mXfowXCtLe+Rxw/lC6ykIIElUEvSGIwl2m6Md1ERfUBv7wN2F9WWkNalnWSMoq5EAgJD3Xrw44LoKRI9NrGO+nX3oBVWyyh6rdDgydt+Jtu1XLJVn+HFwFqWVtcraWy0qi/SN4ljYCiItiuH6qkKaOmflh2uu8WjdMSwi71Hfw7jC45BwC424CktDLMQvoAi2e1xrFU4kUzqd9AvVqkgJ95p8Yxtx9j3S95W83bjF/o16Yb5zaMNgciAQ+jK7cA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: budget
