services:
  client:
    image: registry.timo-hermans.nl/budget-next:api-sep-1
    env_file: ./.env-client
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - budget-network

  api:
    build:
      context: .
      dockerfile: src/Budget.Api/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Database=budget;Username=postgres;Password=P@ssw0rd
      - MessageBus__Host=rabbitmq
    ports:
      - "8888:8080"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - budget-network

  worker:
    build:
      context: .
      dockerfile: src/Budget.Worker/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Database=budget;Username=postgres;Password=P@ssw0rd
      - MessageBus__Host=rabbitmq
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - budget-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: budget
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - budget-network

  rabbitmq:
    image: masstransit/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - budget-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  budget-network:
    driver: bridge
