---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: timo-registry-secret
  namespace: budget
spec:
  encryptedData:
    .dockerconfigjson: AgCg3jCKOxca9NgV1KKTtpN9dKjTQRg79TvnU01rGh0YvqQXYaNowpSnQl+8ixl83/KSpcneNwZf0EHXUm1yiB9Ax1JXSgEcVteonKQPBNnjx3osP5FSAdcr1ptrT8ZYDNPQs4fAK+ungwsDVx4uFGXjOKa27LS3mAb0ygXaq6vQTj2sPuJcrI/fMjOk3VxagLQn5v6FKPrP9EDo1+r5zHAUPlcMfSdzdgvVnY09zIA01elSj8tj9MBfx+1kWMwL8ifXVOcIfv6ncPwBzCC70kpltrr4D8tpXLs0hrPy7U/rZIwiC0ivuRU9tDwuGw/SIDJnoPlIECZ545SYiNPKLdnV7ZKTwtkRXHdHeLUVhdFYC2tU6RpHu31e8q5cAgRNPbeFRC1GHeZIgjjaU0gXMFdRXdDON9esNF7JUBuYuAXTF6mKDiw7qaGPLZns/cbk+BCNoTdNeGZwwy3qyLJYt4RdaZoAxFlPsDQDL+/tXzOSzxsjLJKQlpwY3hum+OS3SuXjsFLXwMVmWJCPQt4ZJWxWehpq5DUIW2d2OBJEO2+mz5ZYmPgY4IqPULZwIaT0Z6yDdPc7MEjmvEqIrT9sQaVVhDKZvQTrwyNTZf5KQHlImEby/MLJin89HzAapPyaEnW31wwZ9YVjrHs8oYbQhjESxRf/CrNgWByrti2+8ZZfEc2aBluSKHqtMyI8+sjMQqv41DWswlWD4elif149T2EC76/CVDH4hRjflSU0ceT1RG3YqJaAaHRSJfR7zEakFLl1O4R3VsXo/9UPp+lVO39uI+KL3bomGWTy7gk5KbIlnVtJQax5MlyGod5rOFV3rjMr3vrKl9se1ADPU0gHgjizwbPul3wWHHtGPWz6iKY5oY1k9ZXYKvCAG9htw6GDPPCH6clq3PauQz2lpWptuqXbVdOb7fMPPvJRW2irPSsRXCtnseAsoEqxOzxo7w==
  template:
    metadata:
      creationTimestamp: null
      name: timo-registry-secret
      namespace: budget
    type: kubernetes.io/dockerconfigjson
