repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  # - name: ingress-nginx
  #   url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: postgres
    namespace: budget
    chart: bitnami/postgresql
    version: 16.7.4
    values:
      - ./helm/postgres/values.yaml

  - name: rabbitmq
    namespace: budget
    chart: bitnami/rabbitmq
    version: 16.0.2
    values:
      - ./helm/rabbitmq/values.yaml

  # - name: nginx-ingress
  #   namespace: ingress-nginx
  #   chart: ingress-nginx/ingress-nginx
  #   version: 4.11.6