apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrations
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600  
  template:
    spec:
      containers:
      - name: ef-migrations
        image: registry.timo-hermans.nl/budget-api-migrations:api-sep-1
        command: ["dotnet", "ef", "database", "update"]
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: backend-db-migrations-configmap
      restartPolicy: Never
