repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgres
    namespace: budget
    chart: bitnami/postgresql
    version: 16.7.4
    values:
      - ./helm/postgres/values.yaml

  - name: rabbitmq
    namespace: budget
    chart: bitnami/rabbitmq
    version: 16.0.2
    values:
      - ./helm/rabbitmq/values.yaml